# Verify every source file, including archive overrides without Git metadata.
# Only SAM's own generated provenance is excluded from a prepared source tree.
function(sam_ggml_tree_hash source result)
    file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${source}" "${source}/*")
    list(FILTER files EXCLUDE REGEX "(^|/)\\.git(/|$)")
    list(FILTER files EXCLUDE REGEX "^\\.sam-(source-fingerprint|precision-provenance)$")
    list(SORT files)
    set(contents "")
    foreach(path IN LISTS files)
        file(SHA256 "${source}/${path}" hash)
        string(APPEND contents "${path}:${hash}\n")
    endforeach()
    string(SHA256 hash "${contents}")
    set(${result} "${hash}" PARENT_SCOPE)
endfunction()

# Verify applicability in a build-local copy, never in a caller checkout.
function(sam_apply_ggml_patch source patch label)
    get_filename_component(parent "${source}" DIRECTORY)
    set(command "${CMAKE_COMMAND}" -E env --unset=GIT_DIR --unset=GIT_WORK_TREE
        "GIT_CEILING_DIRECTORIES=${parent}" "${GIT_EXECUTABLE}" apply)
    execute_process(COMMAND ${command} --check "${patch}" WORKING_DIRECTORY "${source}"
        RESULT_VARIABLE check_result ERROR_VARIABLE check_error)
    if(check_result EQUAL 0)
        execute_process(COMMAND ${command} "${patch}" WORKING_DIRECTORY "${source}"
            RESULT_VARIABLE apply_result ERROR_VARIABLE apply_error)
        if(NOT apply_result EQUAL 0)
            file(REMOVE_RECURSE "${source}")
            message(FATAL_ERROR "Could not apply SAM's GGML ${label} patch: ${apply_error}")
        endif()
    endif()
    execute_process(COMMAND ${command} --reverse --check "${patch}" WORKING_DIRECTORY "${source}"
        RESULT_VARIABLE verified_result ERROR_VARIABLE verified_error)
    if(NOT verified_result EQUAL 0)
        file(REMOVE_RECURSE "${source}")
        message(FATAL_ERROR "GGML ${label} patch verification failed: ${check_error} ${verified_error}")
    endif()
endfunction()

function(sam_prepare_ggml source destination result)
    # Inspect the supplied path before REALPATH can turn an output symlink into
    # an unrelated directory that replacement would recursively delete.
    get_filename_component(destination "${destination}" ABSOLUTE)
    foreach(output IN ITEMS "${destination}" "${destination}.tmp")
        if(IS_SYMLINK "${output}")
            message(FATAL_ERROR "SAM's generated GGML output paths must not be symbolic links: ${output}")
        endif()
    endforeach()
    get_filename_component(source "${source}" REALPATH)
    get_filename_component(destination "${destination}" REALPATH)
    if(NOT EXISTS "${source}/include/ggml.h" OR NOT EXISTS "${source}/CMakeLists.txt")
        message(FATAL_ERROR "SAM requires a GGML source checkout: ${source}")
    endif()
    foreach(output IN ITEMS "${destination}" "${destination}.tmp")
        string(FIND "${output}/" "${source}/" output_in_source)
        string(FIND "${source}/" "${output}/" source_in_output)
        if(output_in_source EQUAL 0 OR source_in_output EQUAL 0)
            message(FATAL_ERROR "SAM's patched GGML copy and supplied source checkout must not overlap")
        endif()
    endforeach()
    set(patch "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patches/ggml-precise-metal.patch")
    if(NOT EXISTS "${patch}")
        message(FATAL_ERROR "SAM's required GGML Metal patch is missing: ${patch}")
    endif()
    set(cuda_patch "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patches/ggml-precise-cuda.patch")
    if(NOT EXISTS "${cuda_patch}")
        message(FATAL_ERROR "SAM's required GGML CUDA patch is missing: ${cuda_patch}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${patch}" "${cuda_patch}")
    set(original_tree_hash "5fc1277d1894e92a0b1a812c3ac88bb46564a2cccd9873e02ad7f8533346b48c")
    set(metal_tree_hash "5816fc926f890714e8a8fa853c428550387f0653794a19537a0ba0b420987c8a")
    set(patched_tree_hash "25e659a3dfac0b16b5d7b455ee7e469b015573e22946aaa57f8a295c875e85c2")
    find_package(Git REQUIRED)
    if(EXISTS "${source}/.git")
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" rev-parse HEAD
            RESULT_VARIABLE revision_result OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT revision_result EQUAL 0 OR NOT revision STREQUAL "353b63b439f27ab2cc19dac97ab1681ba6d2d084")
            message(FATAL_ERROR "SAM's GGML source override must use pinned revision 353b63b439f27ab2cc19dac97ab1681ba6d2d084")
        endif()
    endif()

    # Reconfigure only recopies changed input. Hash contents rather than mtimes;
    # the caller checkout and patch are never modified.
    file(SHA256 "${patch}" patch_hash)
    file(SHA256 "${cuda_patch}" cuda_patch_hash)
    if(NOT cuda_patch_hash STREQUAL "e62f040cf9893f1eebdd8745f4d9a513d91befcbbe7330271bb61b41eb40c8b7")
        message(FATAL_ERROR "SAM's GGML CUDA patch differs from the verified patch")
    endif()
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_FILE}" preparation_hash)
    if(NOT patch_hash STREQUAL "0a0b80dd15c2a8b5a05d148a31e9e53f8df4d0555852ef301da336a9d97b7c48")
        message(FATAL_ERROR "SAM's GGML Metal patch differs from the verified patch")
    endif()
    sam_ggml_tree_hash("${source}" source_tree_hash)
    if(NOT source_tree_hash STREQUAL original_tree_hash AND NOT source_tree_hash STREQUAL metal_tree_hash AND NOT source_tree_hash STREQUAL patched_tree_hash)
        message(FATAL_ERROR "GGML source content differs from the pinned revision or verified precision patches: ${source_tree_hash}")
    endif()
    set(fingerprint_input "${source}\n${source_tree_hash}\n${patch_hash}\n${cuda_patch_hash}\n${preparation_hash}\n")
    string(SHA256 fingerprint "${fingerprint_input}")
    set(stamp "${destination}/.sam-source-fingerprint")
    if(EXISTS "${stamp}")
        file(READ "${stamp}" previous_fingerprint)
    endif()
    set(copy_valid FALSE)
    if(previous_fingerprint STREQUAL fingerprint AND IS_DIRECTORY "${destination}")
        sam_ggml_tree_hash("${destination}" copy_tree_hash)
        if(copy_tree_hash STREQUAL patched_tree_hash)
            set(copy_valid TRUE)
        endif()
    endif()
    if(NOT previous_fingerprint STREQUAL fingerprint OR NOT copy_valid)
        set(temporary "${destination}.tmp")
        file(REMOVE_RECURSE "${temporary}")
        file(MAKE_DIRECTORY "${temporary}")
        file(COPY "${source}/" DESTINATION "${temporary}" PATTERN ".git" EXCLUDE)
        sam_apply_ggml_patch("${temporary}" "${patch}" "Metal")
        sam_apply_ggml_patch("${temporary}" "${cuda_patch}" "CUDA")
        sam_ggml_tree_hash("${temporary}" actual_tree_hash)
        if(NOT actual_tree_hash STREQUAL patched_tree_hash)
            file(REMOVE_RECURSE "${temporary}")
            message(FATAL_ERROR "GGML precision patches produced unexpected source content: ${actual_tree_hash}")
        endif()
        file(WRITE "${temporary}/.sam-precision-provenance"
            "ggml_revision=353b63b439f27ab2cc19dac97ab1681ba6d2d084\npatch_sha256=${patch_hash}\ncuda_patch_sha256=${cuda_patch_hash}\nsource_tree_sha256=${source_tree_hash}\npatched_tree_sha256=${patched_tree_hash}\nsource_fingerprint=${fingerprint}\n")
        file(WRITE "${temporary}/.sam-source-fingerprint" "${fingerprint}")
        file(REMOVE_RECURSE "${destination}")
        file(RENAME "${temporary}" "${destination}")
        message(STATUS "Prepared patched GGML source copy: ${destination}")
    endif()
    set(${result} "${destination}" PARENT_SCOPE)
endfunction()

function(sam_add_ggml source binary)
    # A copied source has no Git metadata. Supply truthful provenance instead of
    # letting upstream rev-parse discover the embedding application's repository.
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patches/ggml-precise-metal.patch" patch_hash)
    string(SUBSTRING "${patch_hash}" 0 12 patch_short_hash)
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patches/ggml-precise-cuda.patch" cuda_patch_hash)
    string(SUBSTRING "${cuda_patch_hash}" 0 12 cuda_patch_short_hash)
    set(GGML_BUILD_COMMIT "353b63b4-sam-${patch_short_hash}-${cuda_patch_short_hash}")
    set(GIT_EXE "")
    add_subdirectory("${source}" "${binary}")
endfunction()
